# 3.2 Arrrays y Matrices

In [6]:
(array_3d <- array(
  1:24,
  dim = c(2, 3, 4),
  dimnames = list(
    c("izquierda", "derecha"),
    c("primero", "segundo", "tercero"),
    c("uno", "dos", "tres", "cuatro")
  )
))
print(array_3d)

, , uno

          primero segundo tercero
izquierda       1       3       5
derecha         2       4       6

, , dos

          primero segundo tercero
izquierda       7       9      11
derecha         8      10      12

, , tres

          primero segundo tercero
izquierda      13      15      17
derecha        14      16      18

, , cuatro

          primero segundo tercero
izquierda      19      21      23
derecha        20      22      24

, , uno

          primero segundo tercero
izquierda       1       3       5
derecha         2       4       6

, , dos

          primero segundo tercero
izquierda       7       9      11
derecha         8      10      12

, , tres

          primero segundo tercero
izquierda      13      15      17
derecha        14      16      18

, , cuatro

          primero segundo tercero
izquierda      19      21      23
derecha        20      22      24



In [3]:
dim(array_3d)
length(dim(array_3d))

[1] 2 3 4

[1] 3

In [7]:
print(array_3d[,1:2,c(2,3)])

, , dos

          primero segundo
izquierda       7       9
derecha         8      10

, , tres

          primero segundo
izquierda      13      15
derecha        14      16



In [8]:
(matriz <- matrix(
  1:6,
  nrow = 3, #ncol = 2 hace lo mismo
  dimnames = list(
    c("uno", "dos", "tres"),
    c("arriba", "abajo")
  )
))

arriba abajo
uno  1      4    
dos  2      5    
tres 3      6

In [10]:
print(matriz[,2])

 uno  dos tres 
   4    5    6 


In [11]:
matriz2 <- matrix(
  3:8,
  nrow = 3, #ncol = 2 hace lo mismo
  dimnames = list(
    c("uno", "dos", "tres"),
    c("arriba", "abajo")
  )
)

matriz + matriz2

arriba abajo
uno  4      10   
dos  6      12   
tres 8      14

# 3.3 Listas y Dataframes

In [13]:
(lista <- list(
  c(1, 2, 3),
  33,
  matrix(c(6, 7, 14, 1), nrow = 2),
  mean
))
print(lista)

[[1]]
[1] 1 2 3

[[2]]
[1] 33

[[3]]
     [,1] [,2]
[1,]    6   14
[2,]    7    1

[[4]]
function (x, ...) 
UseMethod("mean")
<bytecode: 0x5935ccaabd30>
<environment: namespace:base>

[[1]]
[1] 1 2 3

[[2]]
[1] 33

[[3]]
     [,1] [,2]
[1,]    6   14
[2,]    7    1

[[4]]
function (x, ...) 
UseMethod("mean")
<bytecode: 0x5935ccaabd30>
<environment: namespace:base>



In [15]:
names(lista) <- c("vector", "numero", "matriz", "funcion mean")

print(lista)

$vector
[1] 1 2 3

$numero
[1] 33

$matriz
     [,1] [,2]
[1,]    6   14
[2,]    7    1

$`funcion mean`
function (x, ...) 
UseMethod("mean")
<bytecode: 0x5935ccaabd30>
<environment: namespace:base>



In [16]:
print(lista[2:3])

$numero
[1] 33

$matriz
     [,1] [,2]
[1,]    6   14
[2,]    7    1



In [17]:
v <- 1:5
(mi_dataframe <- data.frame(
x = letters[1:5],
y = v,
z = v > 2
))

x y z    
1 a 1 FALSE
2 b 2 FALSE
3 c 3  TRUE
4 d 4  TRUE
5 e 5  TRUE

In [18]:
mi_dataframe[2:3,c(1,2)]

x y
2 b 2
3 c 3

In [19]:
mi_dataframe2 <- data.frame(
col4 = 6:10,
col5 = v+3,
col6 = v < 3
)

cbind(mi_dataframe, mi_dataframe2)

x y z     col4 col5 col6 
1 a 1 FALSE  6   4     TRUE
2 b 2 FALSE  7   5     TRUE
3 c 3  TRUE  8   6    FALSE
4 d 4  TRUE  9   7    FALSE
5 e 5  TRUE 10   8    FALSE

In [21]:
mi_dataframe3 <- data.frame(
x = letters[6:8],
y = 6:8,
z = c(TRUE,FALSE,TRUE)
)

rbind(mi_dataframe, mi_dataframe3)

x y z    
1 a 1 FALSE
2 b 2 FALSE
3 c 3  TRUE
4 d 4  TRUE
5 e 5  TRUE
6 f 6  TRUE
7 g 7 FALSE
8 h 8  TRUE