# 4.2 Arrays con Numpy

### Importar NumPy:

In [1]:
import numpy as np

### Crear arrays a partir de listas:

In [2]:
x1 = np.array([1, 2.1, 3, 4.2, 5])
x2 = np.array([ [1,2,3], [4,5,6], [7,8,9] ])
print(x1)
print(x2)

[1.  2.1 3.  4.2 5. ]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Funciones de NumPy para crear arrays:

In [3]:
x1 = np.zeros(5, dtype=float)
x2 = np.ones((2,2,2), dtype=int)
x3 = np.full((2, 4), 2.78)
x4 = np.random.random((2, 2))
print(x1)
print(x2)
print(x3)
print(x4)

[0. 0. 0. 0. 0.]
[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]
[[2.78 2.78 2.78 2.78]
 [2.78 2.78 2.78 2.78]]
[[0.29139469 0.44806968]
 [0.62525684 0.20914447]]


### Acceso a arrays:

In [4]:
x = np.arange(8)
print(x[3])    # El elemento en la posición 3 (empezando desde 0)
print(x[:4])   # Los 4 primeros elementos
print(x[4:])   # Elementos tras el índice 4
print(x[3:6])  # Elementos intermedios
print(x[1::2]) # Elementos de 2 en 2 desde el de índice 1

3
[0 1 2 3]
[4 5 6 7]
[3 4 5]
[1 3 5 7]


In [5]:
x = np.array([ [1,2,3], [4,5,6], [7,8,9] ])
print(x)
print(x[2:,:2])
print(x[::2,:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[7 8]]
[[1 2 3]
 [7 8 9]]


In [6]:
x = np.array([ [1,2,3], [4,5,6], [7,8,9] ])
y = x[1:3,1:3]
print(x)
print(y)
y[1,1] = 99
print(y)
print(x) 
z = x[:2,:2].copy()
z[0,0] = 88
print(z)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[5 6]
 [8 9]]
[[ 5  6]
 [ 8 99]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 99]]
[[88  2]
 [ 4  5]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 99]]


### Operaciones con arrays:

In [7]:
x1 = np.array([1,2,3,4,5,6])
x2 = np.array([2,3,4,5,6,7])
print(x1+3)
print(x1*3)
print(x1/2)
print(x1+x2)
print(x1/x2)
print(np.exp2(x1))
print(np.power(3,x1))
print(np.log2(x1))
print(np.log10(x1))
print("Suma:  ", np.sum(x1))
print("Min:   ", np.min(x1))
print("Max:   ", np.max(x1))
print("Media: ", np.mean(x1))
print("Std:   ", np.std(x1))
print("Var:   ", np.var(x1))

[4 5 6 7 8 9]
[ 3  6  9 12 15 18]
[0.5 1.  1.5 2.  2.5 3. ]
[ 3  5  7  9 11 13]
[0.5        0.66666667 0.75       0.8        0.83333333 0.85714286]
[ 2.  4.  8. 16. 32. 64.]
[  3   9  27  81 243 729]
[0.         1.         1.5849625  2.         2.32192809 2.5849625 ]
[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125]
Suma:   21
Min:    1
Max:    6
Media:  3.5
Std:    1.707825127659933
Var:    2.9166666666666665


In [8]:
x1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x1+3)
print(x1*3)
print(x1/2)
print(np.exp2(x1))
print(np.power(3,x1))
print(np.log2(x1))
print(np.log10(x1))
print("Suma:  ", np.sum(x1))
print("Min:   ", np.min(x1))
print("Max:   ", np.max(x1))
print("Media: ", np.mean(x1))
print("Std:   ", np.std(x1))
print("Var:   ", np.var(x1))

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]
[[  2.   4.   8.]
 [ 16.  32.  64.]
 [128. 256. 512.]]
[[    3     9    27]
 [   81   243   729]
 [ 2187  6561 19683]]
[[0.         1.         1.5849625 ]
 [2.         2.32192809 2.5849625 ]
 [2.80735492 3.         3.169925  ]]
[[0.         0.30103    0.47712125]
 [0.60205999 0.69897    0.77815125]
 [0.84509804 0.90308999 0.95424251]]
Suma:   45
Min:    1
Max:    9
Media:  5.0
Std:    2.581988897471611
Var:    6.666666666666667
