# 4.2 Arrays con Numpy

### Importar NumPy:

In [1]:
import numpy as np

### Crear arrays a partir de listas:

In [2]:
x1 = np.array([1, 2.1, 3, 4.2, 5])
x2 = np.array([ [1,2,3], [4,5,6], [7,8,9] ])
print(x1)
print(x2)

[1.  2.1 3.  4.2 5. ]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Funciones de NumPy para crear arrays:

In [3]:
x1 = np.zeros(5, dtype=float)
x2 = np.ones((2,2,2), dtype=int)
x3 = np.full((2, 4), 2.78)
x4 = np.random.random((2, 2))
print(x1)
print(x2)
print(x3)
print(x4)

[0. 0. 0. 0. 0.]
[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]
[[2.78 2.78 2.78 2.78]
 [2.78 2.78 2.78 2.78]]
[[0.29139469 0.44806968]
 [0.62525684 0.20914447]]


### Acceso a arrays:

In [4]:
x = np.arange(8)
print(x[3])    # El elemento en la posición 3 (empezando desde 0)
print(x[:4])   # Los 4 primeros elementos
print(x[4:])   # Elementos tras el índice 4
print(x[3:6])  # Elementos intermedios
print(x[1::2]) # Elementos de 2 en 2 desde el de índice 1

3
[0 1 2 3]
[4 5 6 7]
[3 4 5]
[1 3 5 7]


In [5]:
x = np.array([ [1,2,3], [4,5,6], [7,8,9] ])
print(x)
print(x[2:,:2])
print(x[::2,:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[7 8]]
[[1 2 3]
 [7 8 9]]


In [6]:
x = np.array([ [1,2,3], [4,5,6], [7,8,9] ])
y = x[1:3,1:3]
print(x)
print(y)
y[1,1] = 99
print(y)
print(x) 
z = x[:2,:2].copy()
z[0,0] = 88
print(z)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[5 6]
 [8 9]]
[[ 5  6]
 [ 8 99]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 99]]
[[88  2]
 [ 4  5]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 99]]


### Operaciones con arrays:

In [7]:
x1 = np.array([1,2,3,4,5,6])
x2 = np.array([2,3,4,5,6,7])
print(x1+3)
print(x1*3)
print(x1/2)
print(x1+x2)
print(x1/x2)
print(np.exp2(x1))
print(np.power(3,x1))
print(np.log2(x1))
print(np.log10(x1))
print("Suma:  ", np.sum(x1))
print("Min:   ", np.min(x1))
print("Max:   ", np.max(x1))
print("Media: ", np.mean(x1))
print("Std:   ", np.std(x1))
print("Var:   ", np.var(x1))

[4 5 6 7 8 9]
[ 3  6  9 12 15 18]
[0.5 1.  1.5 2.  2.5 3. ]
[ 3  5  7  9 11 13]
[0.5        0.66666667 0.75       0.8        0.83333333 0.85714286]
[ 2.  4.  8. 16. 32. 64.]
[  3   9  27  81 243 729]
[0.         1.         1.5849625  2.         2.32192809 2.5849625 ]
[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125]
Suma:   21
Min:    1
Max:    6
Media:  3.5
Std:    1.707825127659933
Var:    2.9166666666666665


In [8]:
x1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x1+3)
print(x1*3)
print(x1/2)
print(np.exp2(x1))
print(np.power(3,x1))
print(np.log2(x1))
print(np.log10(x1))
print("Suma:  ", np.sum(x1))
print("Min:   ", np.min(x1))
print("Max:   ", np.max(x1))
print("Media: ", np.mean(x1))
print("Std:   ", np.std(x1))
print("Var:   ", np.var(x1))

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]
[[  2.   4.   8.]
 [ 16.  32.  64.]
 [128. 256. 512.]]
[[    3     9    27]
 [   81   243   729]
 [ 2187  6561 19683]]
[[0.         1.         1.5849625 ]
 [2.         2.32192809 2.5849625 ]
 [2.80735492 3.         3.169925  ]]
[[0.         0.30103    0.47712125]
 [0.60205999 0.69897    0.77815125]
 [0.84509804 0.90308999 0.95424251]]
Suma:   45
Min:    1
Max:    9
Media:  5.0
Std:    2.581988897471611
Var:    6.666666666666667


# 4.3 Análisis con Pandas

### Importar Pandas:

In [9]:
import pandas as pd

### Crear DataFrames:

In [10]:
lista = [['Manzana',7],['Pera',9],['Mandarina',11]]
df = pd.DataFrame(lista,columns=['Fruta','Numero'])
print(df)

       Fruta  Numero
0    Manzana       7
1       Pera       9
2  Mandarina      11


### Seleccionar una columna:

In [11]:
lista = [['Manzana',7],['Pera',9],['Mandarina',11]]
df = pd.DataFrame(lista,columns=['Fruta','Numero'])
print(df['Fruta'])

0      Manzana
1         Pera
2    Mandarina
Name: Fruta, dtype: object


### Añadir y eliminar columnas:

In [12]:
lista = [['Manzana',7],['Pera',9],['Mandarina',11]]
df = pd.DataFrame(lista,columns=['Fruta','Numero'])
col = [3,5,7]
print(df)
df['OtroNum'] = col
print(df)
del df['Numero']
print(df)

       Fruta  Numero
0    Manzana       7
1       Pera       9
2  Mandarina      11
       Fruta  Numero  OtroNum
0    Manzana       7        3
1       Pera       9        5
2  Mandarina      11        7
       Fruta  OtroNum
0    Manzana        3
1       Pera        5
2  Mandarina        7


### Tomar filas:

In [13]:
lista = [['Manzana',7],['Pera',9],['Mandarina',11],['Mango',2]]
df = pd.DataFrame(lista,columns=['Fruta','Numero'])
print(df)
print(df[1:3])

       Fruta  Numero
0    Manzana       7
1       Pera       9
2  Mandarina      11
3      Mango       2
       Fruta  Numero
1       Pera       9
2  Mandarina      11


### Añadir y eliminar filas:

In [15]:
lista = [['Manzana',7],['Pera',9]]
lista2 = [['Mandarina',11],['Mango',2]]
df = pd.DataFrame(lista,columns=['Fruta','Numero'])
df2 = pd.DataFrame(lista2,columns=['Fruta','Numero'])
df = pd.concat([df,df2])
print(df)
df = df.drop(1)
print(df)

       Fruta  Numero
0    Manzana       7
1       Pera       9
0  Mandarina      11
1      Mango       2
       Fruta  Numero
0    Manzana       7
0  Mandarina      11


In [18]:
lista = [['Manzana',7],['Pera',9]]
lista2 = [['Mandarina',11],['Mango',2]]
df = pd.DataFrame(lista,columns=['Fruta','Numero'],index=['uno','dos'])
df2 = pd.DataFrame(lista2,columns=['Fruta','Numero'],index=['tres','cuatro'])
df = pd.concat([df,df2])
print(df)
df = df.drop('dos')
print(df)

            Fruta  Numero
uno       Manzana       7
dos          Pera       9
tres    Mandarina      11
cuatro      Mango       2
            Fruta  Numero
uno       Manzana       7
tres    Mandarina      11
cuatro      Mango       2


### Obtener una descripcion de los datos dentro de un DataFrame:

In [19]:
lista = [[1,2,3],[4,5,6],[7,8,9]]
df = pd.DataFrame(lista)
print(df)
print(df.describe())

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9
         0    1    2
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0
